name: Update Gallery JSON

on:
  push:
    paths:
      - 'Assets/gallery/**'

permissions:
  contents: write  # Allow committing changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "action@github.com"

    - name: Generate gallery.json
      run: |
        cd Assets/gallery
        # Only include image files, keep extensions
        ls *.jpg *.jpeg *.png *.gif 2>/dev/null | jq -R -s -c 'split("\n")[:-1] | map("Assets/gallery/" + .)' > gallery.json
        cd ../../
        git add Assets/gallery/gallery.json
        git commit -m "Auto-update gallery.json [skip ci]" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
